//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSE680Week2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public Nullable<int> ContactID { get; set; }
        public int PhoneID { get; set; }
        public Nullable<int> PhoneType { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
